# pihole-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "multus-iot",
            "namespace": "default",
            "mac": "7f:c0:f4:21:8c:1a",
            "ips": ["192.168.0.30/24"]
          }]
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
        - containerPort: 53
        env:
        - name: TZ
          value: "Europe/London"  # Set your timezone
        - name: WEBPASSWORD
          value: "password"       # Set the password for Pi-hole Web UI
        volumeMounts:
        - name: pihole-storage
          mountPath: /etc/pihole
        - name: dnsmasq-storage
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-storage
        persistentVolumeClaim:
          claimName: pihole-pvc
      - name: dnsmasq-storage
        persistentVolumeClaim:
          claimName: pihole-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns-udp
  - protocol: TCP
    port: 53
    targetPort: 53
    name: dns-tcp
  type: NodePort
