kind: PersistentVolume
apiVersion: v1
metadata:
  name: zigbee-data-pv
  namespace: zigbee
  labels:
    app: zigbee
spec:
  capacity:
    storage: 10Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /volume1/k3s/projects/zigbee2mqtt  # Static path on the NFS server
    server: 192.168.0.2               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain
